name=PicoFlashEeprom
version=1.1.0
author=Julian
maintainer=Julian
sentence=Arduino library with advanced configurable logging.
paragraph=An Arduino C++ library for Pico Flash Eeprom featuring selectable log levels, timestamps, and runtime configuration.
category=Flash Eeprom
url=https://github.com/britesc/PicoFlashEeprom
architectures=2040, 2350